### ISSUE TITLE
ValueError: Timezone offset does not match system offset

### ISSUE THREAD

**Issue by archman** [archman/PyArchAppl#1]
Happens when importing `archappl`.
```
>>> import archappl
[15:34:35.101] WARNING: archappl: Not running in Jupyter Notebook
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/archappl/__init__.py", line 58, in <module>
    from archappl.client import *
  File "/usr/lib/python3/dist-packages/archappl/client/__init__.py", line 2, in <module>
    from archappl.data import ArchiverDataClient
  File "/usr/lib/python3/dist-packages/archappl/data/__init__.py", line 1, in <module>
    from .client import ArchiverDataClient
  File "/usr/lib/python3/dist-packages/archappl/data/client.py", line 8, in <module>
    from .utils import LOCAL_ZONE_NAME
  File "/usr/lib/python3/dist-packages/archappl/data/utils.py", line 12, in <module>
    LOCAL_ZONE = tzlocal.get_localzone()
  File "/usr/lib/python3/dist-packages/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/lib/python3/dist-packages/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
 File "/usr/lib/python3/dist-packages/tzlocal/utils.py", line 46, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: 0 != -18000. Please, check your config files.
```

**Comment by archman** [comment]
Either solution below should fix the issue:
- ``sudo dpkg-reconfigure tzdata``
-  ``export TZ="/usr/share/zoneinfo/America/New_York" # or other zoneinfo``
